### ISSUE TITLE
Add Pyrylium cation to rules for thiele

### ISSUE THREAD

**Issue by tagirshin** [stsouko/CGRtools#163]
I have found that pyrylium cations and similar cycles cannot be converted from thiel to kekule form (raises InvalidAromaticRing exception). However, these are definitely aromatic compounds and this example molecule is not wrong. 

Is it possible to add a new rule for them?

![pyr](https://user-images.githubusercontent.com/17476642/107754913-6bcf5e80-6d22-11eb-83b0-8f4089f9100b.png)
<img width="978" alt="Снимок экрана 2021-02-12 в 11 11 23" src="https://user-images.githubusercontent.com/17476642/107755414-0d56b000-6d23-11eb-8061-7d6c9b36b772.png">

**Comment by stsouko** [comment]
todo: add

**Comment by stsouko** [comment]
fixed.
commit 822bd77
