### ISSUE TITLE
Scaffold and/or framework extraction

### ISSUE THREAD

**Issue by tagirshin** [stsouko/CGRtools#169]
Is it possbile to add method, that extracts Bemis-Murcko scaffold from the given molecular graph?

**Comment by stsouko** [comment]
PR welcome

**Comment by UnixJunkie** [comment]
There is code in there:
https://github.com/UnixJunkie/molenc/blob/master/bin/molenc_scaffold.py

**Comment by UnixJunkie** [comment]
The implementation in rdkit is not faithful to "BM frameworks" as described in the seminal Bemis-Murcko paper.
My code was also sent to the rdkit mailing list.

**Comment by stsouko** [comment]
in CGRtools BMF can be extracted by calling `skin_graph` property.

    m = CGRtools.smiles('CC(C)C1=CC=C(C=C1)C1=CC=CC=C1')
    bmf = m.skin_graph  # bmf is dict of sets adjacency matrix

If you want molecule object e.g. for smiles generation.

    bmm = MoleculeContainer()
    seen = set()
    for a in bmf:
        bmm.add_atom('C', a)
    for a, bs in bmf.items():
        seen.add(a)
        for b in bs:
            if b not in seen:
                bmm.add_bond(a, b, 1)
