### ISSUE TITLE
Canonical tautomer definition

### ISSUE THREAD

**Issue by JHucker** [stsouko/CGRtools#171]
Regarding the tautomerize function, what defines the canonical form? Is this similar to rdkit's empirical scoring scheme or otherwise?

**Comment by stsouko** [comment]
Hi.
`tautomerize` method currently experimental. canonical form selection based on Huckel's method of delocalized electrons energy calculation and number of aromatic rings. Lower energy and more aromatic rings are preferable.

I have not compared this approach with MolVS/Rdkit scoring function.
I plan to do this on a Nicklaus dataset and choose the appropriate one.

**Comment by JHucker** [comment]
Excellent, thanks for the information.
