### ISSUE TITLE
Query isomorphism unexepected behaviour

### ISSUE THREAD

**Issue by tagirshin** [stsouko/CGRtools#172]
I wanted to create a query from SMILES, so I decided to use molecule.substructure(as_query=True). Then I needed to use isomorphism, but it didn't work as I expected:

<img width="659" alt="Снимок экрана 2021-05-19 в 09 14 35" src="https://user-images.githubusercontent.com/17476642/118771293-ac3efb00-b882-11eb-8b58-9fbbba549e98.png">

Next, I decided to delete all hybridization and neighbors marks, but it didn't change anything:

<img width="659" alt="Снимок экрана 2021-05-19 в 09 09 16" src="https://user-images.githubusercontent.com/17476642/118770682-e5c33680-b881-11eb-868f-67d7824384a0.png">

Finally, when I constructed query myself, it worked as supposed:

<img width="659" alt="Снимок экрана 2021-05-19 в 09 12 12" src="https://user-images.githubusercontent.com/17476642/118771026-4e121800-b882-11eb-8d17-d33f550137da.png">

So, I don't understand if it is supposed to be like that or it's a bug.

Notebook to reproduce this experiment:
[query_bug.ipynb.zip](https://github.com/stsouko/CGRtools/files/6506683/query_bug.ipynb.zip)

**Comment by stsouko** [comment]
Molecule Queries now have extra attrs.
implicit_hydrogens - for searching atoms with specified amount of hydrogens.
ring_sizes - for searching atoms in rings.

For example double bonded CC fragment in 6-member ring where one of atoms contains only one implicit H.
```
query = QueryContainer()
query.add_atom('C', rings_sizes=6)
query.add_atom('C', rings_sizes=6, hydrogens=1)
query.add_bond(1, 2, 2)
```

This is fix:

```
for _, atom in query.atoms():
    atom.neighbors = None
    atom.hybridization = None
    atom.implicit_hydrogens = None
    atom.ring_sizes = None
query
```

**Comment by tagirshin** [comment]
Thanks a lot!
