### ISSUE TITLE
Errors in pytest (no module lazy_object_proxy)

### ISSUE THREAD

**Issue by aigulkhkmv** [stsouko/CGRtools#192]
Hello!

I have installed CDRtools as described in the READMe. But then I run tests:
`pytest --pyargs CGRtools`, I have the error: `ModuleNotFoundError: No module named 'lazy_object_proxy'`. 

This problem is easily solved by additional installation of this library: `pip install lazy_object_proxy`

Maybe it is better to add this library depending on the CGRtools? Or maybe add additional command (```pip install lazy_object_proxy```) to the README?

**Comment by stsouko** [comment]
fixed: e20a9c7
at the moment tests don't cover large part of code.
