### ISSUE TITLE
[Errno 2] No such file or directory: 'molecules.dat'

### ISSUE THREAD

**Issue by KhuzaimahAziz** [stsouko/CGRtools#197]
I'm new to CGRtools and when I follow the tutorial given on the documentation it shows me this error [Errno 2] No such file or directory: 'molecules.dat'. I don't know what is causing this problem. Your help will be really appreciated. Thanks.

**Comment by stsouko** [comment]
Hi Aziz, did you properly download tutorial folder?
Make sure you have all files from link in same directory.
https://github.com/stsouko/CGRtools/tree/4.1/doc/tutorial

**Comment by KhuzaimahAziz** [comment]
Oh. Thank you so much. I did not even came across this folder. I will let you know when it works.

**Comment by KhuzaimahAziz** [comment]
Done it worked. Thanks alot
