### ISSUE TITLE
Calculation of Molecular Descriptors

### ISSUE THREAD

**Issue by KhuzaimahAziz** [stsouko/CGRtools#198]
Hello again, I wanted to ask that can this tool calculate Molecular Descriptors? If yes then where can I find the method of doing so. Thanks

**Comment by stsouko** [comment]
CGRtools don't contain any descriptors generation code.
You can use https://github.com/cimm-kzn/CIMtools for descriptors generation.

CIMtools use CGRtools molecules objects. You can find some tutorials in repo.

**Comment by KhuzaimahAziz** [comment]
Okay sir. I will look into it. Thanks
